#include "core.h"

#include "core_Algorithm.h"
#include "core_AlgorithmInfo.h"
#include "core_FileStorage.h"
#include "core_InputArray.h"
#include "core_Mat.h"
#include "core_MatExpr.h"
#include "core_OutputArray.h"
#include "core_PCA.h"
#include "core_RNG.h"
#include "core_SparseMat.h"
#include "core_SVD.h"
