#include "ml.h"

#include "ml_StatModel.h"
#include "ml_ANN_MLP.h"
#include "ml_Boost.h"
#include "ml_DTrees.h"
#include "ml_EM.h"
#include "ml_KNearest.h"
#include "ml_LogisticRegression.h"
#include "ml_NormalBayesClassifier.h"
#include "ml_RTrees.h"
#include "ml_SVM.h"
