// Additional types

#pragma once

#include "my_functions.h"

#include <bit>
#include <type_traits>

namespace cv
{
    typedef cv::Vec<uchar, 6> Vec6b;
    typedef cv::Vec<short, 6> Vec6s;
    typedef cv::Vec<ushort, 6> Vec6w;
}

// -------------------------------------------------------------------------
// P/Invoke boundary value types (namespace `interop`)
//
// These are plain-old-data (standard-layout, trivially copyable) structs
// used ONLY as by-value parameters and return values of the extern "C"
// (CVAPI) functions. They intentionally mirror the memory layout of the
// matching cv:: types (cv::Point, cv::Size, cv::Rect, cv::Scalar, ...) but
// carry no constructors/methods, because:
//
//   1. The cv:: geometry types are C++ classes. Passing a C++ UDT by value
//      through C linkage (extern "C") is only conditionally supported, makes
//      the ABI fragile across compilers, and triggers MSVC warning C4190.
//      POD structs give a stable, portable C ABI that the C# side marshals
//      1:1 via [StructLayout] structs.
//   2. They decouple the P/Invoke wire format from OpenCV: if a cv:: type
//      changes, only the c()/cpp() converters below need updating, not the
//      ABI seen by managed code.
//
// Convert at the boundary with the overloaded helpers: cpp(interop::X) ->
// cv::X for incoming arguments and c(cv::X) -> interop::X for outgoing
// values. Do NOT use cv:: types directly by value in CVAPI signatures.
//
// For layout-identical POD/cv:: pairs the converters are generated by the
// OCS_INTEROP_BITCAST macro, which std::bit_cast between the two and
// static_asserts that their sizes match and both are trivially copyable, so
// any future layout drift is caught at compile time. Types that need real
// computation (e.g. Moments::inv_sqrt_m00) or whose cv:: counterpart is not
// trivially copyable (cv::Scalar / cv::Vec derive from cv::Matx, which has
// user-provided copy/move members) keep explicit converters.
// -------------------------------------------------------------------------
namespace interop
{
#pragma region OpenCV1.0-compatible Types

    struct Point
    {
        int x;
        int y;
    };
    struct Point2f
    {
        float x;
        float y;
    };
    struct Point2d
    {
        double x;
        double y;
    };

    struct Point3i
    {
        int x;
        int y;
        int z;
    };
    struct Point3f
    {
        float x;
        float y;
        float z;
    };
    struct Point3d
    {
        double x;
        double y;
        double z;
    };

    struct Size
    {
        int width;
        int height;
    };
    struct Size2f
    {
        float width;
        float height;
    };
    struct Size2d
    {
        double width;
        double height;
    };

    struct Rect
    {
        int x;
        int y;
        int width;
        int height;
    };
    struct Rect2f
    {
        float x;
        float y;
        float width;
        float height;
    };
    struct Rect2d
    {
        double x;
        double y;
        double width;
        double height;
    };

    struct Scalar
    {
        double val[4];
    };

    struct Range
    {
        int  start_index, end_index;
    };

    struct Moments
    {
        double  m00, m10, m01, m20, m11, m02, m30, m21, m12, m03; /* spatial moments */
        double  mu20, mu11, mu02, mu30, mu21, mu12, mu03; /* central moments */
        double  inv_sqrt_m00; /* m00 != 0 ? 1/sqrt(m00) : 0 */
    };

    struct TermCriteria
    {
        int    type;
        int    max_iter;
        double epsilon;
    };

    struct RotatedRect
    {
        Point2f center;
        Size2f  size;
        float angle;
    };

    struct KeyPoint
    {
        Point2f pt;
        float size;
        float angle;
        float response;
        int octave;
        int class_id;
    };

    struct DMatch
    {
        int queryIdx;
        int trainIdx;
        int imgIdx;
        float distance;
    };

#pragma endregion

    typedef struct Vec2b { uchar val[2]; } Vec2b;
    typedef struct Vec3b { uchar val[3]; } Vec3b;
    typedef struct Vec4b { uchar val[4]; } Vec4b;
    typedef struct Vec6b { uchar val[6]; } Vec6b;
    typedef struct Vec2s { short val[2]; } Vec2s;
    typedef struct Vec3s { short val[3]; } Vec3s;
    typedef struct Vec4s { short val[4]; } Vec4s;
    typedef struct Vec6s { short val[6]; } Vec6s;
    typedef struct Vec2w { ushort val[2]; } Vec2w;
    typedef struct Vec3w { ushort val[3]; } Vec3w;
    typedef struct Vec4w { ushort val[4]; } Vec4w;
    typedef struct Vec6w { ushort val[6]; } Vec6w;
    typedef struct Vec2i { int val[2]; } Vec2i;
    typedef struct Vec3i { int val[3]; } Vec3i;
    typedef struct Vec4i { int val[4]; } Vec4i;
    typedef struct Vec6i { int val[6]; } Vec6i;
    typedef struct Vec2f { float val[2]; } Vec2f;
    typedef struct Vec3f { float val[3]; } Vec3f;
    typedef struct Vec4f { float val[4]; } Vec4f;
    typedef struct Vec6f { float val[6]; } Vec6f;
    typedef struct Vec2d { double val[2]; } Vec2d;
    typedef struct Vec3d { double val[3]; } Vec3d;
    typedef struct Vec4d { double val[4]; } Vec4d;
    typedef struct Vec6d { double val[6]; } Vec6d;

    // Stack-only array proxy for the ref-struct InputArray/OutputArray redesign. It mirrors
    // cv::_InputArray/_OutputArray (a kind tag + a pointer/inline payload) and is passed BY VALUE
    // across the P/Invoke boundary, so the managed side never allocates a heap cv::_InputArray per
    // call. The native side rebuilds a cv::_InputArray/_OutputArray on its own stack from these
    // fields via fromInputProxy()/fromOutputProxy().
    //
    // For Scalar kinds the inline payload feeds a stack-local cv::Scalar (see fromInputProxy). For
    // Vec kinds the cv::_InputArray references this struct's own `payload` storage; because the
    // proxy is taken by value, the parameter copy stays valid for the duration of the OpenCV call.
    struct ArrayProxy
    {
        void  *handle;     // cv::Mat*/cv::UMat*/cv::MatExpr* for handle kinds; null otherwise
        int    kind;       // ArrayProxyKind: 0 None, 1 Mat, 2 UMat, 3 MatExpr, 4 Scalar, 5 Double, 6 Vec
        int    vecDepth;   // Vec only: CV_8U..CV_64F element depth; otherwise 0
        int    vecLength;  // Vec only: element count (2/3/4/6); otherwise 0
        double payload[6]; // inline storage: Scalar (4 doubles) | double (1) | Vec (raw bytes, <= 48)
    };

} // namespace interop

extern "C"
{
    /** @brief Structure containing image keypoints and descriptors. */
    struct CV_EXPORTS_W_SIMPLE detail_ImageFeatures
    {
        int img_idx;
        interop::Size img_size;
        std::vector<cv::KeyPoint>* keypoints;
        cv::Mat* descriptors;
    };

    /*
    struct line_descriptor_KeyLine
    {
        float angle;
        int class_id;
        int octave;
        interop::Point2f pt;
        float response;
        float size;
        float startPointX;
        float startPointY;
        float endPointX;
        float endPointY;
        float sPointInOctaveX;
        float sPointInOctaveY;
        float ePointInOctaveX;
        float ePointInOctaveY;
        float lineLength;
        int numOfPixels;
    };*/
}

// bit_cast-based converter pair for layout-identical POD <-> cv:: types.
// static_assert catches any future layout/trivial-copyability drift.
#define OCS_INTEROP_BITCAST(INTEROP_TYPE, CV_TYPE)                                                     \
    static_assert(sizeof(interop::INTEROP_TYPE) == sizeof(CV_TYPE)                                     \
        && std::is_trivially_copyable_v<interop::INTEROP_TYPE>                                         \
        && std::is_trivially_copyable_v<CV_TYPE>,                                                      \
        "interop POD layout mismatch: " #INTEROP_TYPE " vs " #CV_TYPE);                                \
    static interop::INTEROP_TYPE c(const CV_TYPE &v) { return std::bit_cast<interop::INTEROP_TYPE>(v); } \
    static CV_TYPE cpp(const interop::INTEROP_TYPE &v) { return std::bit_cast<CV_TYPE>(v); }

OCS_INTEROP_BITCAST(Point, cv::Point)
OCS_INTEROP_BITCAST(Point2f, cv::Point2f)
OCS_INTEROP_BITCAST(Point2d, cv::Point2d)
OCS_INTEROP_BITCAST(Point3i, cv::Point3i)
OCS_INTEROP_BITCAST(Point3d, cv::Point3d)
OCS_INTEROP_BITCAST(Size, cv::Size)
OCS_INTEROP_BITCAST(Size2f, cv::Size2f)
OCS_INTEROP_BITCAST(Size2d, cv::Size2d)
OCS_INTEROP_BITCAST(Rect, cv::Rect)
OCS_INTEROP_BITCAST(Rect2f, cv::Rect2f)
OCS_INTEROP_BITCAST(Rect2d, cv::Rect2d)
OCS_INTEROP_BITCAST(Range, cv::Range)
OCS_INTEROP_BITCAST(TermCriteria, cv::TermCriteria)
OCS_INTEROP_BITCAST(RotatedRect, cv::RotatedRect)
OCS_INTEROP_BITCAST(KeyPoint, cv::KeyPoint)
OCS_INTEROP_BITCAST(DMatch, cv::DMatch)

#undef OCS_INTEROP_BITCAST

// cv::Scalar / cv::Vec derive from cv::Matx, which declares user-provided
// copy/move members, so they are NOT trivially copyable and cannot be
// bit_cast. Keep explicit field-wise converters for them.
static interop::Scalar c(const cv::Scalar &s)
{
    interop::Scalar ret{};
    ret.val[0] = s[0];
    ret.val[1] = s[1];
    ret.val[2] = s[2];
    ret.val[3] = s[3];
    return ret;
}
static cv::Scalar cpp(const interop::Scalar &s)
{
    return {s.val[0], s.val[1], s.val[2], s.val[3]};
}

static interop::Vec4i c(const cv::Vec4i &v)
{
    interop::Vec4i vv{};
    vv.val[0] = v.val[0];
    vv.val[1] = v.val[1];
    vv.val[2] = v.val[2];
    vv.val[3] = v.val[3];
    return vv;
}
static cv::Vec4i cpp(const interop::Vec4i &v)
{
    return cv::Vec4i(v.val[0], v.val[1], v.val[2], v.val[3]);
}

// Converts a jagged array of interop::Rect into nested std::vector<cv::Rect>.
// (Replaces the legacy CvRect-based toVec path; CvRect was dropped from the
// OpenCV 5 public include chain.)
static void toRectVec(
    const interop::Rect **inPtr, const int size1, const int *size2, std::vector<std::vector<cv::Rect> > &outVec)
{
    outVec.resize(size1);
    for (int i = 0; i < size1; i++)
    {
        const int size = size2[i];
        const interop::Rect *p = inPtr[i];
        std::vector<cv::Rect> v;
        v.reserve(size);
        for (int j = 0; j < size; j++)
            v.push_back(cpp(p[j]));
        outVec[i] = std::move(v);
    }
}

// Moments needs real computation (inv_sqrt_m00; cpp reconstructs from the
// spatial moments only), so it keeps explicit converters.
static interop::Moments c(const cv::Moments &m)
{
    interop::Moments ret;
    ret.m00 = m.m00; ret.m10 = m.m10; ret.m01 = m.m01;
    ret.m20 = m.m20; ret.m11 = m.m11; ret.m02 = m.m02;
    ret.m30 = m.m30; ret.m21 = m.m21; ret.m12 = m.m12; ret.m03 = m.m03;
    ret.mu20 = m.mu20; ret.mu11 = m.mu11; ret.mu02 = m.mu02;
    ret.mu30 = m.mu30; ret.mu21 = m.mu21; ret.mu12 = m.mu12; ret.mu03 = m.mu03;
    const double am00 = std::abs(m.m00);
    ret.inv_sqrt_m00 = am00 > DBL_EPSILON ? 1. / std::sqrt(am00) : 0;

    return ret;
}
static cv::Moments cpp(const interop::Moments &m)
{
    return cv::Moments(m.m00, m.m10, m.m01, m.m20, m.m11, m.m02, m.m30, m.m21, m.m12, m.m03);
}

// -------------------------------------------------------------------------
// interop::ArrayProxy -> cv::_InputArray / _OutputArray / _InputOutputArray
//
// These build the cv:: array proxy on the caller's stack from a by-value
// interop::ArrayProxy, so no heap cv::_InputArray is allocated per call. Use
// them at the head of a CVAPI body, e.g.:
//
//     CVAPI(...) foo(interop::ArrayProxy src, interop::ArrayProxy dst) {
//         return cvTry([&] {
//         cv::Scalar s; // scratch storage for scalar-kind inputs (see below)
//         cv::bar(fromInputProxy(src, s), fromOutputProxy(dst));
//         });
//     }
//
// Scalar/Double inputs: cv::_InputArray references a cv::Scalar, so the caller
// must keep `scalarScratch` alive for the whole OpenCV call (one scratch per
// input that may be a scalar).
// Vec inputs: cv::_InputArray references proxy.payload; the by-value parameter
// copy stays valid for the call.
// -------------------------------------------------------------------------
static cv::_InputArray fromInputProxy(const interop::ArrayProxy &p, cv::Scalar &scalarScratch)
{
    switch (p.kind)
    {
    case 1: return cv::_InputArray(*static_cast<cv::Mat *>(p.handle));
    case 2: return cv::_InputArray(*static_cast<cv::UMat *>(p.handle));
    case 3: return cv::_InputArray(*static_cast<cv::MatExpr *>(p.handle));
    case 4:
    case 5:
        scalarScratch = cv::Scalar(p.payload[0], p.payload[1], p.payload[2], p.payload[3]);
        return cv::_InputArray(scalarScratch);
    case 6:
        switch (p.vecDepth)
        {
        case CV_8U:  return cv::_InputArray(reinterpret_cast<const uchar  *>(p.payload), p.vecLength);
        case CV_8S:  return cv::_InputArray(reinterpret_cast<const schar  *>(p.payload), p.vecLength);
        case CV_16U: return cv::_InputArray(reinterpret_cast<const ushort *>(p.payload), p.vecLength);
        case CV_16S: return cv::_InputArray(reinterpret_cast<const short  *>(p.payload), p.vecLength);
        case CV_32S: return cv::_InputArray(reinterpret_cast<const int    *>(p.payload), p.vecLength);
        case CV_32F: return cv::_InputArray(reinterpret_cast<const float  *>(p.payload), p.vecLength);
        case CV_64F: return cv::_InputArray(reinterpret_cast<const double *>(p.payload), p.vecLength);
        default:     return cv::noArray();
        }
    case 7: return *static_cast<cv::_InputArray *>(p.handle); // RawInputArray (class InputArray)
    default: return cv::noArray();
    }
}

static cv::_OutputArray fromOutputProxy(const interop::ArrayProxy &p)
{
    switch (p.kind)
    {
    case 1: return cv::_OutputArray(*static_cast<cv::Mat *>(p.handle));
    case 2: return cv::_OutputArray(*static_cast<cv::UMat *>(p.handle));
    case 8: return *static_cast<cv::_OutputArray *>(p.handle); // RawOutputArray (class OutputArray)
    default: return cv::noArray();
    }
}

static cv::_InputOutputArray fromInputOutputProxy(const interop::ArrayProxy &p)
{
    switch (p.kind)
    {
    case 1: return cv::_InputOutputArray(*static_cast<cv::Mat *>(p.handle));
    case 2: return cv::_InputOutputArray(*static_cast<cv::UMat *>(p.handle));
    case 9: return *static_cast<cv::_InputOutputArray *>(p.handle); // RawInputOutputArray (class)
    default: return cv::noArray();
    }
}
