using Xunit;
using OpenCvSharp.Cuda;
using Xunit.Sdk;

namespace OpenCvSharp.Tests.Cuda;

public class CudaStereoTest : CudaTestBase
{
    [Fact]
    public void DrawColorDisp_Test()
    {
        VerifyCudaSupport();

        // 1. Arrange: Create a 1-channel disparity map (100x100)
        using var cpuDisp = new Mat(100, 100, MatType.CV_8UC1, new Scalar(30));
        using var gpuDisp = new GpuMat(); gpuDisp.Upload(cpuDisp);
        using var gpuColor = new GpuMat();

        // 2. Act: Draw colored disparity
        Cv2.Cuda.DrawColorDisp(gpuDisp, gpuColor, ndisp: 64);

        // 3. Download and Assert
        using var cpuColor = new Mat();
        gpuColor.Download(cpuColor);

        Assert.False(cpuColor.Empty());

        // The CUDA drawColorDisp implementation typically outputs CV_8UC4 (BGRA)
        Assert.Equal(4, cpuColor.Channels());
        Assert.Equal(MatType.CV_8UC4, cpuColor.Type());

        // Ensure the rows/cols match
        Assert.Equal(100, cpuColor.Rows);
        Assert.Equal(100, cpuColor.Cols);
    }

    [Fact]
    public void ReprojectImageTo3D_Test()
    {
        VerifyCudaSupport();

        // 1. Arrange: 10x10 disparity map filled with value 10
        using var cpuDisp = new Mat(10, 10, MatType.CV_8UC1, new Scalar(10));
        using var gpuDisp = new GpuMat(); gpuDisp.Upload(cpuDisp);

        // 2. Simple Q Matrix (4x4)
        // Typically generated by cv::stereoRectify
        double[] qData = {
                1, 0, 0, -5,
                0, 1, 0, -5,
                0, 0, 0, 50,
                0, 0, 1/16.0, 0
            };
        using var Q = Mat.FromPixelData(4, 4, MatType.CV_32F, qData);

        // 3. Act: Reproject to 3D with 3 channels (XYZ)
        using var gpu3D = new GpuMat();
        Cv2.Cuda.ReprojectImageTo3D(gpuDisp, gpu3D,Q, dstCn: 3);

        // 4. Assert
        using var cpu3D = new Mat();
        gpu3D.Download(cpu3D);

        Assert.False(cpu3D.Empty());
        Assert.Equal(3, cpu3D.Channels());
        Assert.Equal(MatType.CV_32FC3, cpu3D.Type());

        // Verify coordinate dimensions
        Assert.Equal(10, cpu3D.Rows);
        Assert.Equal(10, cpu3D.Cols);

        // Verify a point has non-zero Z coordinate
        Vec3f point = cpu3D.At<Vec3f>(5, 5);
        Assert.NotEqual(0, point.Item2); // Z should be calculated
    }


}

