using OpenCvSharp.OptFlow;
using Xunit;

namespace OpenCvSharp.Tests.OptFlow;

public class OpticalFlowPCAFlowTest : TestBase
{
    private static (Mat prev, Mat next) MakeShiftedPair()
    {
        var prev = new Mat(64, 64, MatType.CV_8UC1, Scalar.All(0));
        Cv2.Rectangle(prev, new Rect(20, 20, 16, 16), Scalar.All(255), -1);
        var next = new Mat(64, 64, MatType.CV_8UC1, Scalar.All(0));
        Cv2.Rectangle(next, new Rect(22, 20, 16, 16), Scalar.All(255), -1); // shifted +2 px in x
        return (prev, next);
    }

    [Fact]
    public void CreateAndDisposeWithoutPrior()
    {
        using var flow = OpticalFlowPCAFlow.Create();
    }

    [Fact]
    public void CreateWithCustomParameters()
    {
        using var flow = OpticalFlowPCAFlow.Create(
            basisSize: new Size(10, 8),
            sparseRate: 0.05f,
            retainedCornersFraction: 0.3f,
            occlusionsThreshold: 0.001f,
            dampingFactor: 0.0001f,
            claheClip: 10f);
    }

    [Fact]
    public void CreateViaCv2Factory()
    {
        using var flow = Cv2.OptFlow.CreateOptFlow_PCAFlow();
    }

    [Fact(Skip = "requires a prior file generated by the upstream learn_prior.py script, not available in this repo")]
    public void CreateWithPrior()
    {
        // PCAPrior needs a prior file trained offline via opencv_contrib's learn_prior.py.
        // No such fixture is checked into this repository, so this documents the intended usage.
        using var prior = new PCAPrior("prior.bin");
        using var flow = OpticalFlowPCAFlow.Create(prior);
    }

    [Fact]
    public void Calc()
    {
        var (prev, next) = MakeShiftedPair();
        using (prev)
        using (next)
        using (var flow = OpticalFlowPCAFlow.Create())
        using (var flowMat = new Mat())
        {
            flow.Calc(prev, next, flowMat);

            Assert.Equal(prev.Size(), flowMat.Size());
            Assert.Equal(2, flowMat.Channels());
        }
    }

    [Fact]
    public void CollectGarbage()
    {
        using var flow = OpticalFlowPCAFlow.Create();
        flow.CollectGarbage();
    }
}
