using OpenCvSharp.Internal;

namespace OpenCvSharp.OptFlow;

/// <summary>
/// This class can be used for imposing a learned prior on the resulting optical flow.
/// Solution will be regularized according to this prior.
/// You need to generate an appropriate prior file with the "learn_prior.py" script beforehand.
/// </summary>
public class PCAPrior : CvPtrObject
{
    private PCAPrior((IntPtr smartPtr, IntPtr rawPtr) ptrs)
        : base(ptrs.smartPtr, ptrs.rawPtr,
            static h => NativeMethods.HandleException(NativeMethods.optflow_Ptr_PCAPrior_delete(h)))
    {
    }

    /// <summary>
    /// Loads a learned prior from the given file.
    /// </summary>
    /// <param name="pathToPrior">Path to a prior file generated by the "learn_prior.py" script.</param>
    public PCAPrior(string pathToPrior)
        : this(Create(pathToPrior))
    {
    }

    private static (IntPtr smartPtr, IntPtr rawPtr) Create(string pathToPrior)
    {
        ArgumentNullException.ThrowIfNull(pathToPrior);

        NativeMethods.HandleException(
            NativeMethods.optflow_PCAPrior_new(pathToPrior, out var smartPtr));
        NativeMethods.HandleException(
            NativeMethods.optflow_Ptr_PCAPrior_get(smartPtr, out var rawPtr));
        return (smartPtr, rawPtr);
    }

    /// <summary>
    /// Padding size (derived from the loaded prior).
    /// </summary>
    public int Padding
    {
        get
        {
            ThrowIfDisposed();
            NativeMethods.HandleException(NativeMethods.optflow_PCAPrior_getPadding(Handle, out var ret));
            return ret;
        }
    }

    /// <summary>
    /// Number of basis vectors (derived from the loaded prior).
    /// </summary>
    public int BasisSize
    {
        get
        {
            ThrowIfDisposed();
            NativeMethods.HandleException(NativeMethods.optflow_PCAPrior_getBasisSize(Handle, out var ret));
            return ret;
        }
    }
}
